### ISSUE TITLE
fix CI using the new pip command

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio4py#15]
@kennychowdhary 
Now that pressio4py can be installed using pip (see this: https://pypi.org/project/pressio4py/) we need to change the github action commands. To do so, the new action should be updated to include the following steps: 
```
export CXX=path-to-c++-compiler
cd <the-current-branch-to-run-action-on>
cd pressio/; git pull; git checkout develop; cd -

# build pressio4py
python setup.py build
# run unit tests
cd build; pytest; cd -

python setup.py install 
# run regression tests
pytest 
```
(2) Also, we need to verify that the build works for several c++ compiler versions. 

(3) `python3 setup.py sdist bdist_wheel`

**Comment by kennychowdhary** [comment]
So when you run `cd build; pytest` you get an error that pytest cannot find the pressio4py module. It works after you run setup install, but we probably should fix this. One option is to use the command `python -m pytest dir_to_so_file/` which automatically addds dir_to_so_file to the python path.

**Comment by fnrizzi** [comment]
that solution `python -m ...` is fine for me :)

**Comment by kennychowdhary** [comment]
I'll try the python -m.

**Comment by fnrizzi** [comment]
Coolbeans!

**Comment by kennychowdhary** [comment]
So I tried python -m pytest in the build/ directory and no luck. This is because the *.so file is not in the build directory. On my local machine, if I go into lib*/ directory and run it from there it works. I made this fix to the git hub action so now unit testing works without installing.

**Comment by kennychowdhary** [comment]
Ok check it out now. Everything is in and working.

**Comment by fnrizzi** [comment]
@kennychowdhary thanks!!! 
what are these warnings? 

![image](https://user-images.githubusercontent.com/18708772/104434635-bcb92f00-558b-11eb-8ddc-9b920304ab6a.png)

**Comment by fnrizzi** [comment]
@kennychowdhary

**Comment by kennychowdhary** [comment]
Fixed the warning issues!
