### ISSUE TITLE
cmake: automate creation of regression tests  

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio4py#5]
Currently we have a non-scalable way to create regression tests, see the cmakelists inside the `tests/regression`. 
Need to automate the creation so that we don't add each test individually. 
But we need to come up with a convention to name them .

**Comment by kennychowdhary** [comment]
I automated the process for now. See the CMakeLists in the regression test folder. Let's talk about naming conventions and possibly changing the paths of the test directories.

**Comment by fnrizzi** [comment]
@kennychowdhary thanks! 
Can you please think/propose a naming convention?

**Comment by fnrizzi** [comment]
@kennychowdhary 
```
# # Get all reg test directories and copy them, along with their contents
# file(GLOB REG_TEST_FOLDERS_SRC ${CMAKE_CURRENT_SOURCE_DIR}/*)
# message("Source DIR for reg test : " ${REG_TEST_FOLDERS_SRC})
# file(COPY ${REG_TEST_FOLDERS_SRC} DESTINATION ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
# # Cops the Apps directory as well
# file(COPY ${PRESSIO4PY_APPS_DIR} DESTINATION ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})
```
this does not work. If I make a change to Python script in the source code, and I do make again in the build directory, the change is not updated.
