### ISSUE TITLE
add action to develop branch too 

### ISSUE THREAD

**Issue by fnrizzi** [Pressio/pressio4py#6]
need to automate building and testing for develop branch too

**Comment by kennychowdhary** [comment]
Ok done. I added a github action to the develop branch. It actually failed to build pressio4py. The first error was this:

/home/runner/pressio_repos/pressio4py/src/types.hpp:78:46: error: ‘DenseMatrix’ in namespace ‘pressio::containers’ does not name a template type

If you click on the Actions tab and the most recent action run on the develop branch, you can see the error messages in more detail.

**Comment by kennychowdhary** [comment]
Looks like it's not a problem anymore, but I will explore it on my machine. The latest github action to build and test pressio4py passed as of 11-12-202.
